from typing import TypedDict, Any, List, Dict, Annotated
from langgraph.graph import MessagesState

def replace_value(current, new):
    return new if new is not None else current

class LoopAIState(MessagesState):
    task_id: str
    mined_data: str  # to defined the path of mined data
    output_dir: str  # to defined the path of output directory
    # configer state attributes
    configer_error: Annotated[str, replace_value]  # the errors of configer, it can indicate the LLM to summarize the configer statement
    configer_statement: str  # the statement of configer generated by LLM
    # judger state attributes
    eval_model_path: str  # to defined the path of model to be evaluated and post-trained
    eval_base_url: str  # to defined the base url of model to be evaluated and post-trained
    eval_api_key: str  # to defined the api key of model to be evaluated and post-trained
    # to defined the temperature of model to be evaluated and post-trained
    eval_temperature: float = 0
    # to defined the top_p of model to be evaluated and post-trained
    eval_top_p: float = 0.95
    eval_test_case_path: str  # to defined the path of test case to be evaluated
    eval_problem_path: str  # to defined the path of problem to be evaluated
    eval_result_path: str  # No need to be set, computed during runtime to defined the path of result of model to be evaluated
    eval_batch_size: int = 20  # to defined the batch size of model to be evaluated
    # analyzer state attributes
    analyze_task_type: str = 'code'
    analyze_batch_size: int = 20  # to defined the batch size of model to be analyzed
    analyze_model_path: str  # to defined the path of model to be analyzed and post-trained
    analyze_base_url: str  # to defined the base url of model to be analyzed and post-trained
    analyze_api_key: str  # to defined the api key of model to be analyzed and post-trained
    analyze_temperature: float = 0 # to defined the temperature of model to be analyzed and post-trained
    analyze_top_p: float = 0.95 # to defined the top_p of model to be analyzed and post-trained
    output_brief: bool  # whether to output brief analysis
    analyze_output_result_path: str  # No need to be set, computed during runtime to defined the path of result to be outputted
    analyze_output_summary_path: str  # No need to be set, computed during runtime to defined the path of summary to be outputted
    analyze_sampling_top_k: int = 5  # the number of failure examples to be sampled
    analyze_output_report_json_path: str  # No need to be set, computed during runtime to defined the path of report to be outputted
    analyze_output_report_text_path: str  # No need to be set, computed during runtime to defined the path of report to be outputted
    output_suggestion: bool # whether to output suggestion
    analyze_output_suggestion_path: str  # No need to be set, computed during runtime to defined the path of suggestion to be outputted
    #
    update_model_path: str  # to defined the save path of the post-trained model
    # obtainer state attributes
    obtainer_model_path: str  # to defined the path of model for obtainer agent
    obtainer_base_url: str  # to defined the base url of model for obtainer agent
    obtainer_api_key: str  # to defined the api key of model for obtainer agent
    obtainer_temperature: float = 0.7  # to defined the temperature of model for obtainer agent
    obtainer_search_engine: str = "tavily"  # search engine to use (tavily, duckduckgo, jina)
    obtainer_max_urls: int = 10  # maximum number of URLs to visit
    obtainer_max_download_subtasks: int = None  # maximum number of download subtasks
    # RAG configuration (independent from obtainer)
    obtainer_reset_rag: bool = False  # whether to reset RAG database
    obtainer_rag_embed_model: str = ""  # RAG embedding model (default: "text-embedding-3-large")
    obtainer_rag_collection_name: str = "rag_collection"  # RAG collection name
    obtainer_rag_api_base_url: str = ""  # RAG API base URL (if empty, uses obtainer's base_url)
    obtainer_rag_api_key: str = ""  # RAG API key (if empty, uses obtainer's api_key)
    obtainer_research_summary: str  # research summary generated by summary agent
    obtainer_subtasks: List[Dict[str, Any]]  # download subtasks generated
    obtainer_urls_visited: List[str]  # URLs visited during web search
    obtainer_download_results: Dict[str, Any]  # download execution results
    obtainer_kaggle_username: str = ""  # Kaggle username for API authentication
    obtainer_kaggle_key: str = ""  # Kaggle API key for authentication
    obtainer_tavily_api_key: str = ""  # Tavily API key for web search
    obtainer_category: str = "PT"  # data category for post-processing (PT or SFT)
    obtainer_postprocess_results: Dict[str, Any]  # post-processing results
    obtainer_debug: bool = False  # enable debug mode for obtainer agent (logs all levels and saves to file)

    # graph state attributes
    current: str  # to defined the current task, e.g. train, evaluate, obtain, naive
    next_to: Annotated[str, replace_value]  # defined the next node to be executed, usually is used by the feedback node, the value of node name should exists in the current graph.
    automated_query: Annotated[str, replace_value] # the automated query of the current task, if it is not None, the query will be used to replace the user query
    exception: Annotated[str, replace_value] # the exception of the current task, e.g. the error message of the model evaluation

class RuntimeContext(TypedDict):
    exception_navigate: str # the exception node name to navigate of the current task, e.g. feedback_node
