from typing import TypedDict, Any, List, Dict, Annotated
from langgraph.graph import MessagesState

def replace_value(current, new):
    return new if new is not None else current

class LoopAIState(MessagesState):
    task_id: str
    mined_data: str  # to defined the path of mined data
    output_dir: str  # to defined the path of output directory
    # configer state attributes
    configer_error: Annotated[str, replace_value]  # the errors of configer, it can indicate the LLM to summarize the configer statement
    configer_statement: str  # the statement of configer generated by LLM
    # judger state attributes
    eval_model_path: str  # to defined the path of model to be evaluated and post-trained
    eval_base_url: str  # to defined the base url of model to be evaluated and post-trained
    eval_api_key: str  # to defined the api key of model to be evaluated and post-trained
    # to defined the temperature of model to be evaluated and post-trained
    eval_temperature: float = 0
    # to defined the top_p of model to be evaluated and post-trained
    eval_top_p: float = 0.95
    eval_test_case_path: str  # to defined the path of test case to be evaluated
    eval_problem_path: str  # to defined the path of problem to be evaluated
    eval_result_path: str  # No need to be set, computed during runtime to defined the path of result of model to be evaluated
    eval_batch_size: int = 20  # to defined the batch size of model to be evaluated
    # analyzer state attributes
    analyze_task_type: str = 'code'
    analyze_batch_size: int = 20  # to defined the batch size of model to be analyzed
    analyze_model_path: str  # to defined the path of model to be analyzed and post-trained
    analyze_base_url: str  # to defined the base url of model to be analyzed and post-trained
    analyze_api_key: str  # to defined the api key of model to be analyzed and post-trained
    analyze_temperature: float = 0 # to defined the temperature of model to be analyzed and post-trained
    analyze_top_p: float = 0.95 # to defined the top_p of model to be analyzed and post-trained
    output_brief: bool  # whether to output brief analysis
    analyze_output_result_path: str  # No need to be set, computed during runtime to defined the path of result to be outputted
    analyze_output_summary_path: str  # No need to be set, computed during runtime to defined the path of summary to be outputted
    analyze_sampling_top_k: int = 5  # the number of failure examples to be sampled
    analyze_output_report_json_path: str  # No need to be set, computed during runtime to defined the path of report to be outputted
    analyze_output_report_text_path: str  # No need to be set, computed during runtime to defined the path of report to be outputted
    output_suggestion: bool # whether to output suggestion
    analyze_output_suggestion_path: str  # No need to be set, computed during runtime to defined the path of suggestion to be outputted
    #
    update_model_path: str  # to defined the save path of the post-trained model
    # obtainer state attributes
    obtainer_model_path: str  # to defined the path of model for obtainer agent
    obtainer_base_url: str  # to defined the base url of model for obtainer agent
    obtainer_api_key: str  # to defined the api key of model for obtainer agent
    obtainer_temperature: float = 0.7  # to defined the temperature of model for obtainer agent
    obtainer_search_engine: str = "tavily"  # search engine to use (tavily, duckduckgo, jina)
    obtainer_max_urls: int = 10  # maximum number of URLs to visit
    obtainer_max_download_subtasks: int = None  # maximum number of download subtasks
    # RAG configuration (independent from obtainer)
    obtainer_reset_rag: bool = True  # whether to reset RAG database
    obtainer_rag_embed_model: str = ""  # RAG embedding model (default: "text-embedding-3-large")
    obtainer_rag_collection_name: str = "rag_collection"  # RAG collection name
    obtainer_rag_api_base_url: str = ""  # RAG API base URL (if empty, uses obtainer's base_url)
    obtainer_rag_api_key: str = ""  # RAG API key (if empty, uses obtainer's api_key)
    obtainer_research_summary: str  # research summary generated by summary agent
    obtainer_subtasks: List[Dict[str, Any]]  # download subtasks generated
    obtainer_urls_visited: List[str]  # URLs visited during web search
    obtainer_download_results: Dict[str, Any]  # download execution results
    obtainer_kaggle_username: str = ""  # Kaggle username for API authentication
    obtainer_kaggle_key: str = ""  # Kaggle API key for authentication
    obtainer_tavily_api_key: str = ""  # Tavily API key for web search
    obtainer_category: str = "PT"  # data category for post-processing (PT or SFT)
    obtainer_postprocess_results: Dict[str, Any]  # post-processing results
    obtainer_debug: bool = False  # enable debug mode for obtainer agent (logs all levels and saves to file)
    # mapping subgraph state attributes
    obtainer_default_mapping_format: str="alpaca"
    obtainer_intent_type: str = ""  # dataset_request or eval_recommendation
    obtainer_normalized_query: str = ""  # rewritten dataset request if input was eval-based
    obtainer_normalized_reason: str = ""  # reason for normalization
    obtainer_intermediate_data_path: str = ""  # path to intermediate format data
    obtainer_mapping_user_intent: str = ""  # user intent: list_formats, preset_format, custom_format
    obtainer_mapping_selected_format_id: str = ""  # selected preset format ID (e.g., alpaca, chatml)
    obtainer_mapping_custom_description: str = ""  # custom format description from user
    obtainer_pending_format: Dict[str, Any] = None  # pending format waiting for user confirmation
    obtainer_confirmed_format: Dict[str, Any] = None  # confirmed format for mapping
    obtainer_confirmation_result: str = ""  # confirmation result: confirmed, modify, restart
    obtainer_mapping_auto_mode: bool = True  # whether mapping is in auto mode (skip user interaction)
    obtainer_mapping_results: Dict[str, Any] = None  # mapping execution results

    # trainer state attributes
    train_dataset_path: str  # to defined the path of training dataset (json/jsonl format)
    train_task_description: str  # to defined the task description for training
    train_config_template_path: str  # to defined the path of llamafactory config template
    train_config_output_path: str  # to defined the path of generated training config
    train_output_dir: str  # to defined the output directory for training
    train_model_name: str  # to defined the base model name for training
    train_use_swanlab: bool = True  # whether to use swanlab for monitoring
    train_swanlab_project: str  # to defined the swanlab project name
    
    # trainer workflow state fields
    data_check_passed: bool = False  # whether data check passed
    data_check_result: dict = {}  # data check result details
    data_check_report_path: str = ""  # path to data check report
    data_check_error: str = ""  # data check error message
    config_generation_success: bool = False  # whether config generation succeeded
    config_explanation_path: str = ""  # path to config explanation
    config_generation_error: str = ""  # config generation error message
    training_success: bool = False  # whether training succeeded
    training_execution_time: float = 0.0  # training execution time
    training_task_id: str = ""  # remote training task id
    training_final_status: dict = {}  # final training status
    training_log_path: str = ""  # path to training log
    training_report_path: str = ""  # path to training report
    training_error: str = ""  # training error message
    training_service_url: str = "http://localhost:8000"  # training service URL
    current_training_status: str = ""  # current training status
    update_model_path: str  # to defined the save path of the post-trained model

    # graph state attributes
    current: str  # to defined the current task, e.g. train, evaluate, obtain, naive
    next_to: Annotated[str, replace_value]  # defined the next node to be executed, usually is used by the feedback node, the value of node name should exists in the current graph.
    automated_query: Annotated[str, replace_value] # the automated query of the current task, if it is not None, the query will be used to replace the user query
    exception: Annotated[str, replace_value] # the exception of the current task, e.g. the error message of the model evaluation

class RuntimeContext(TypedDict):
    exception_navigate: str # the exception node name to navigate of the current task, e.g. feedback_node
